// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/forgot-password" | "/invite" | "/login" | "/org/[slug]" | "/org/[slug]/members" | "/org/[slug]/projects/[id]" | "/org/[slug]/projects/[id]/settings" | "/org/[slug]/projects/new" | "/org/[slug]/settings" | "/org/[slug]/settings/ai" | "/register" | "/reset-password" | "/settings"
type AppRouteHandlerRoutes = "/api/ai/analyze" | "/api/auth/forgot-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register" | "/api/auth/reset-password" | "/api/invitations/[token]" | "/api/invitations/[token]/accept" | "/api/organizations" | "/api/organizations/[id]" | "/api/organizations/[id]/ai-settings" | "/api/organizations/[id]/invitations" | "/api/organizations/[id]/invitations/[invitationId]" | "/api/organizations/[id]/invitations/[invitationId]/resend" | "/api/organizations/[id]/members" | "/api/organizations/[id]/members/[memberId]" | "/api/organizations/[id]/projects" | "/api/organizations/check-slug" | "/api/projects" | "/api/projects/[id]" | "/api/projects/[id]/connections" | "/api/projects/[id]/nodes" | "/api/projects/[id]/nodes/[nodeId]" | "/api/projects/[id]/nodes/[nodeId]/deviations" | "/api/projects/[id]/nodes/positions" | "/api/user/password" | "/api/user/profile"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/analyze": {}
  "/api/auth/forgot-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/invitations/[token]": { "token": string; }
  "/api/invitations/[token]/accept": { "token": string; }
  "/api/organizations": {}
  "/api/organizations/[id]": { "id": string; }
  "/api/organizations/[id]/ai-settings": { "id": string; }
  "/api/organizations/[id]/invitations": { "id": string; }
  "/api/organizations/[id]/invitations/[invitationId]": { "id": string; "invitationId": string; }
  "/api/organizations/[id]/invitations/[invitationId]/resend": { "id": string; "invitationId": string; }
  "/api/organizations/[id]/members": { "id": string; }
  "/api/organizations/[id]/members/[memberId]": { "id": string; "memberId": string; }
  "/api/organizations/[id]/projects": { "id": string; }
  "/api/organizations/check-slug": {}
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/projects/[id]/connections": { "id": string; }
  "/api/projects/[id]/nodes": { "id": string; }
  "/api/projects/[id]/nodes/[nodeId]": { "id": string; "nodeId": string; }
  "/api/projects/[id]/nodes/[nodeId]/deviations": { "id": string; "nodeId": string; }
  "/api/projects/[id]/nodes/positions": { "id": string; }
  "/api/user/password": {}
  "/api/user/profile": {}
  "/forgot-password": {}
  "/invite": {}
  "/login": {}
  "/org/[slug]": { "slug": string; }
  "/org/[slug]/members": { "slug": string; }
  "/org/[slug]/projects/[id]": { "slug": string; "id": string; }
  "/org/[slug]/projects/[id]/settings": { "slug": string; "id": string; }
  "/org/[slug]/projects/new": { "slug": string; }
  "/org/[slug]/settings": { "slug": string; }
  "/org/[slug]/settings/ai": { "slug": string; }
  "/register": {}
  "/reset-password": {}
  "/settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
