// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/org/[slug]/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/[slug]/members">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/org/[slug]/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/org/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/org/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/org/[slug]/projects/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/[slug]/projects/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/org/[slug]/projects/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/org/[slug]/projects/[id]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/[slug]/projects/[id]/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/org/[slug]/projects/[id]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/org/[slug]/projects/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/[slug]/projects/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/org/[slug]/projects/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/org/[slug]/settings/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/[slug]/settings/ai">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/org/[slug]/settings/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/org/[slug]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/[slug]/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/org/[slug]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/analyze">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/invitations/[token]/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invitations/[token]/accept">> = Specific
  const handler = {} as typeof import("../../../src/app/api/invitations/[token]/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/invitations/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invitations/[token]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/invitations/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/[id]/ai-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[id]/ai-settings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/[id]/ai-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/[id]/invitations/[invitationId]/resend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[id]/invitations/[invitationId]/resend">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/[id]/invitations/[invitationId]/resend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/[id]/invitations/[invitationId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[id]/invitations/[invitationId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/[id]/invitations/[invitationId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/[id]/invitations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[id]/invitations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/[id]/invitations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/[id]/members/[memberId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[id]/members/[memberId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/[id]/members/[memberId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/[id]/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[id]/members">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/[id]/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/[id]/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[id]/projects">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/[id]/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/check-slug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/check-slug">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/check-slug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/connections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/connections">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/connections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/nodes/[nodeId]/deviations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/nodes/[nodeId]/deviations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/nodes/[nodeId]/deviations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/nodes/[nodeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/nodes/[nodeId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/nodes/[nodeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/nodes/positions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/nodes/positions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/nodes/positions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/nodes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/nodes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/nodes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
